engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:

ratings:
   paths:
   - "src/**/*"

exclude_paths:
- lib/**/*
- __tests__/**/*
